'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { apiGet, apiPost } from '@/lib/api';
import { ReviewData, TitleOption, ThumbnailOption, SelectReviewRequest } from '@/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

export default function ReviewPage({ params }: { params: { id: string } }) {
  const router = useRouter();
  const { id } = params;

  const [reviewData, setReviewData] = useState<ReviewData | null>(null);
  const [selectedTitleId, setSelectedTitleId] = useState<string>('');
  const [selectedThumbId, setSelectedThumbId] = useState<string>('');
  const [publishing, setPublishing] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadData() {
      try {
        setLoading(true);
        const data = await apiGet<ReviewData>(`/stories/${id}/review`);
        setReviewData(data);
      } catch (err) {
        console.error('Failed to load review data:', err);
        setError('Failed to load review data.');
      } finally {
        setLoading(false);
      }
    }

    if (id) {
      loadData();
    }
  }, [id]);

  const handlePublish = async () => {
    if (!reviewData || !selectedTitleId || !selectedThumbId) return;

    try {
      setPublishing(true);

      // 1. Select title + thumbnail
      await apiPost<void>(`/stories/${id}/review`, {
        title_option_id: selectedTitleId,
        thumbnail_option_id: selectedThumbId,
      } satisfies SelectReviewRequest);

      // 2. Trigger publish (YouTube upload)
      await apiPost<void>(`/stories/${id}/publish`);

      // 3. Redirect
      router.push(`/stories/${id}`);

    } catch (err) {
      console.error('Publish failed:', err);
      alert('Failed to start publishing process.');
    } finally {
      setPublishing(false);
    }
  };

  if (loading) {
    return <div className="p-8 text-center">Loading review data...</div>;
  }

  if (error || !reviewData) {
    return <div className="p-8 text-center text-red-500">{error ?? 'Story not found.'}</div>;
  }

  const { title_options: titles, thumbnail_options: thumbnails, video_url: videoUrl, metadata } = reviewData;
  const description = (metadata?.description as string) ?? '';
  const tags = (metadata?.tags as string[]) ?? [];

  return (
    <div className="mx-auto max-w-5xl space-y-8 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Final Review</h1>
          <p className="text-muted-foreground">Select the best assets before publishing to YouTube.</p>
        </div>
        <Badge variant="outline" className="text-lg uppercase">
          ready for review
        </Badge>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Left Column: Video & Metadata */}
        <div className="space-y-6">
          <Card className="overflow-hidden border-zinc-800 bg-zinc-950/50">
            <CardHeader>
              <CardTitle>Video Preview</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              {videoUrl ? (
                <video
                  controls
                  className="w-full bg-black aspect-video"
                  src={videoUrl}
                >
                  Your browser does not support the video tag.
                </video>
              ) : (
                <div className="flex h-64 items-center justify-center bg-zinc-900 text-zinc-500">
                  Video not available
                </div>
              )}
            </CardContent>
          </Card>

          <Card className="border-zinc-800 bg-zinc-950/30">
            <CardHeader>
              <CardTitle>Metadata</CardTitle>
              <CardDescription>Generated by AI</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {description && (
                <div className="space-y-2">
                  <p className="text-sm font-medium text-zinc-400">Description</p>
                  <p className="whitespace-pre-wrap rounded-lg bg-zinc-900/50 p-3 text-sm font-mono">
                    {description}
                  </p>
                </div>
              )}
              {tags.length > 0 && (
                <div className="space-y-2">
                  <p className="text-sm font-medium text-zinc-400">Tags</p>
                  <div className="flex flex-wrap gap-2">
                    {tags.map((tag, i) => (
                      <Badge key={i} variant="secondary" className="text-xs">
                        {tag}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Right Column: Titles & Thumbs */}
        <div className="space-y-6">
          {/* Titles */}
          <Card className="border-zinc-800 bg-zinc-950/30">
            <CardHeader>
              <CardTitle>Select Title</CardTitle>
            </CardHeader>
            <CardContent className="grid gap-3">
              {titles.length > 0 ? (
                titles.map((t: TitleOption) => (
                  <label
                    key={t.id}
                    className={`flex cursor-pointer items-center justify-between rounded-lg border p-4 transition-all hover:bg-zinc-900 ${
                      selectedTitleId === t.id
                        ? 'border-green-500 bg-green-950/10 ring-1 ring-green-500'
                        : 'border-zinc-800 bg-zinc-900/50'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <input
                        type="radio"
                        name="title"
                        value={t.id}
                        checked={selectedTitleId === t.id}
                        onChange={() => setSelectedTitleId(t.id)}
                        className="h-4 w-4 border-zinc-600 bg-zinc-900 text-green-500 focus:ring-green-500"
                      />
                      <span className="font-medium">{t.title_text}</span>
                    </div>
                  </label>
                ))
              ) : (
                <p className="text-sm text-zinc-500">No titles generated yet.</p>
              )}
            </CardContent>
          </Card>

          {/* Thumbnails */}
          <Card className="border-zinc-800 bg-zinc-950/30">
            <CardHeader>
              <CardTitle>Select Thumbnail</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                {thumbnails.length > 0 ? (
                  thumbnails.map((thumb: ThumbnailOption) => (
                    <div
                      key={thumb.id}
                      onClick={() => setSelectedThumbId(thumb.id)}
                      className={`relative cursor-pointer overflow-hidden rounded-lg border-2 transition-all ${
                        selectedThumbId === thumb.id
                          ? 'border-green-500 shadow-[0_0_15px_rgba(34,197,94,0.3)]'
                          : 'border-transparent hover:border-zinc-700'
                      }`}
                    >
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src={thumb.image_url}
                        alt="Thumbnail option"
                        className="aspect-video w-full object-cover"
                      />
                    </div>
                  ))
                ) : (
                   <p className="col-span-2 text-sm text-zinc-500">No thumbnails generated yet.</p>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Action */}
          <div className="pt-4">
            <Button
              size="lg"
              className="w-full bg-green-600 hover:bg-green-700 text-white font-bold text-lg h-14"
              disabled={!selectedTitleId || !selectedThumbId || publishing}
              onClick={handlePublish}
            >
              {publishing ? 'Publishing...' : 'CONFIRM & PUBLISH'}
            </Button>
            <p className="mt-2 text-center text-xs text-zinc-500">
              This will upload the video to YouTube.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
